=== POLIJIC/HechosHistoricosXML/HechosHistoricos.dtd
<!ELEMENT HechosHistoricos (HechosHistorico)+>
<!ATTLIST HechosHistorico descripcion CDATA #REQUIRED>
<!ELEMENT HechosHistorico (Fecha,Epoca?, PersonajeDestacado*)?>
<!ELEMENT Epoca EMPTY>
<!ELEMENT PersonajeDestacado ANY>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT FechaNacimiento (#PCDATA)>
<!ELEMENT Fecha (#PCDATA | FormatoFecha)*>
<!ELEMENT FormatoFecha (Dia,Mes,Año)>
<!ELEMENT Dia (#PCDATA)>
<!ELEMENT Año (#PCDATA)>
<!ELEMENT Mes (#PCDATA)>

=== POLIJIC/HechosHistoricosXML/HechosHistoricos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HechosHistoricos SYSTEM "HechosHistoricos.dtd">
<HechosHistoricos>
    <HechosHistorico descripcion="">
        <Fecha>
            <FormatoFecha>
                <Dia>25</Dia>
                <Mes>10</Mes>
                <Año>2020</Año>
            </FormatoFecha>
        </Fecha>
        <Epoca/>
        <PersonajeDestacado>

        </PersonajeDestacado>
    </HechosHistorico>
    <HechosHistorico descripcion="">
        <Fecha>
            22-67-56
        </Fecha>
        <Epoca/>
        <PersonajeDestacado>

        </PersonajeDestacado>
    </HechosHistorico>

</HechosHistoricos>
